default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: devit_development

test:
  <<: *default
  database: devit_test

production:
  <<: *default
  database: devit_production
  username: devit

